### PR TITLE
Improved ci

### PR DESCRIPTION
**Pull request by AdrieanKhisbe**
Improved CI, Rework tests with lab :)

### CODE REVIEW

**Comment by AdrieanKhisbe** [comment]
Fixed the PR. ;)
(had forgot I didn't had complete the job)

**Comment by AdrieanKhisbe** [comment]
Improved tests.

**Comment by AdrieanKhisbe** [comment]
> $ touch this # cc @rjrodger

**Comment by rjrodger** [comment]
merged!
Thank you :)

**Comment by AdrieanKhisbe** [comment]
Great!, 
You're welcome :)

**Pull request merged**
